name: dl
channels:
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - astor=0.8.0
  - blas=1.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - console_shortcut=0.1.1
  - cudatoolkit=9.0
  - cudnn=7.6.5
  - gast=0.3.3
  - grpcio=1.27.2
  - h5py=2.8.0
  - hdf5=1.8.18
  - icc_rt=2019.0.0
  - intel-openmp=2020.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - libprotobuf=3.12.3
  - markdown=3.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openssl=1.1.1g
  - pip=20.1.1
  - protobuf=3.12.3
  - python=3.7.7
  - pyyaml=5.3.1
  - scipy=1.5.0
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.32.3
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wincertstore=0.2
  - wrapt=1.12.1
  - yaml=0.1.7
  - zlib=1.2.11
  - scikit-image=0.16.2
  - scikit-learn=0.23.2
  - pip:
    - csbdeep==0.6.2
    - cycler==0.10.0
    - imagecodecs==2020.5.30
    - keras==2.2.5
    - kiwisolver==1.2.0
    - matplotlib==3.2.2
    - n2v==0.2.1
    - pillow==7.2.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - ruamel-yaml==0.16.10
    - ruamel-yaml-clib==0.2.0
    - tifffile==2020.6.3
    - tqdm==4.47.0
    - stardist==0.7.1
    - packaging==20.9
